//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D03_EF6_FirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int CursoID { get; set; }
        public int SubareaCursoID { get; set; }
        public string NomeCurso { get; set; }
        public decimal Duracao { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
    
        public virtual SubareaCurso SubareaCurso { get; set; }
    }
}
