//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D03_EF6_FirstDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestaoFormacaoDBEntities : DbContext
    {
        public GestaoFormacaoDBEntities()
            : base("name=GestaoFormacaoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaCurso> AreaCurso { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<SubareaCurso> SubareaCurso { get; set; }
    }
}
