//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D03_EF6_FirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubareaCurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubareaCurso()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public int SubareaCursoID { get; set; }
        public int AreaCursoID { get; set; }
        public string Subarea { get; set; }
    
        public virtual AreaCurso AreaCurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
